"""add app images and metadata

Revision ID: add_app_images_metadata
Revises: cascade_delete_constraints
Create Date: 2026-01-25 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_app_images_metadata'
down_revision = 'cascade_delete_constraints'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('apps', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('apps', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('apps', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('apps', sa.Column('demo_url', sa.String(), nullable=True))
    op.add_column('apps', sa.Column('support_email', sa.String(), nullable=True))
    op.add_column('apps', sa.Column('website_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'website_url')
    op.drop_column('apps', 'support_email')
    op.drop_column('apps', 'demo_url')
    op.drop_column('apps', 'features')
    op.drop_column('apps', 'tags')
    op.drop_column('apps', 'logo_url')
    op.drop_column('apps', 'images')
    # ### end Alembic commands ###